title: CalMoyenne
description: Extension Firefox pour le calcul automatique des moyennes
theme: jekyll-theme-cayman
show_downloads: true
github:
  is_project_page: true
  repository_url: https://github.com/HZC23/Calmoyenne 